# Generated by Django 4.2.10 on 2024-02-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
