# Generated by Django 4.2.10 on 2024-02-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper_api', '0003_alter_vessel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('naccs', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('departure_location', models.CharField(default='TBA', max_length=200)),
                ('arrival_location', models.CharField(default='TBA', max_length=200)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
