# Generated by Django 4.2.10 on 2024-02-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipper_api', '0002_alter_vessel_created_at_alter_vessel_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
